/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AirtableDebug: typeof import('./components/AirtableDebug.vue')['default']
    AppointmentFilters: typeof import('./components/appointments/AppointmentFilters.vue')['default']
    AppointmentList: typeof import('./components/appointments/AppointmentList.vue')['default']
    AppointmentPagination: typeof import('./components/appointments/AppointmentPagination.vue')['default']
    AppointmentStatusCard: typeof import('./components/appointments/AppointmentStatusCard.vue')['default']
    CreateAppointmentModal: typeof import('./components/appointments/CreateAppointmentModal.vue')['default']
    EditAppointmentModal: typeof import('./components/appointments/EditAppointmentModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
